### ISSUE TITLE
Second and subsequent attempt of obtaining highquality clay does not required addition of clay

### ISSUE THREAD

**Issue by hohserg1** [GoogeTan/PhoenixProject#2]
How to reproduce:
1. Place barrel
2. Insert water
3. Insert clay
4. Jump. Plum-plum-plum!
5. Take highquality clay
6. Insert only water
7. Jump. Plum-plum-plum!
8. Take highquality clay

**Comment by hohserg1** [comment]
https://user-images.githubusercontent.com/35610168/103463797-3a856b00-4d40-11eb-80c5-59d54e5a770c.mp4

**Comment by GoogeTan** [comment]
Fixed
